name: State Labels Manager
description:
  A GitHub Action for managing issue and PR labels as structured state,
  supporting flexible label formats and CRUD operations
author: FidelusAleksander

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: tag
  color: blue

# Define your inputs here.
inputs:
  operation:
    description: 'Action to perform: set, remove, get, get-all'
    required: true
  issue-number:
    description:
      'Issue or PR number to operate on (auto-detected from context if not
      provided)'
    required: false
  github-token:
    description: 'GitHub token for authentication'
    required: false
    default: ${{ github.token }}
  key:
    description: 'State key to set/remove/get (required for all except get-all)'
    required: false
  value:
    description: 'Value to set for set operations'
    required: false
  prefix:
    description: 'Label prefix (e.g., state)'
    required: false
    default: 'state'
  separator:
    description: 'Separator between label parts (e.g., ::)'
    required: false
    default: '::'
  repository:
    description: 'Repository in owner/repo format'
    required: false
    default: ${{ github.repository }}
  delete-unused-labels:
    description: >-
      Whether to delete labels from the repository when they are removed/unset
      (only if not used by other issues/PRs)
    required: false
    default: 'false'

# Define your outputs here.
outputs:
  state:
    description: 'JSON string of all state key/values (for get-all operation)'
  value:
    description: 'Value of the requested key (for get operation)'
  success:
    description: 'Boolean indicating if the operation succeeded'

runs:
  using: node24
  main: dist/index.js
